<div id="cvmanagment">

<?php
//echo "<pre>";
//print_r($selecteduserid);
//echo "</pre>";
?>

<?php
//echo "<pre>";
//print_r($userdata);
//echo "</pre>";
?>
	<b style='color:blue'>User:</b></br></br>
	<div id = "users" style="margin-left:20px">		
	<select id="seluser" size='1'>
	<?php foreach($userdata as $user):?>
		<option id='<?php echo $user->getId();?>'
		<?php if ($user->getId() == $selecteduserid) {echo 'selected'; $cur_user = $user;} ?>><?php echo $user->getName(); ?></option>
    <?php endforeach; ?>
	</select>
	<a id = "<?php echo $selecteduserid; ?>" class="delete-user">Delete This User</a>&nbsp;|&nbsp
	<a id = "<?php echo $selecteduserid; ?>" class="save-user">Save This User</a>&nbsp;|&nbsp
	<a class="add-user">Add New User</a>
	</br>
		<table>
			<tr>
				<td>
				<b>Name:</b>
				</td>
				<td><textarea class='user-fields' id="name"><?php echo $cur_user->getName(); ?></textarea></td>
			</tr>
			<tr>
				<td>
				<b>E-mail:</b>
				</td>
				<td><textarea class='user-fields' id="email"><?php echo $cur_user->getEmail(); ?></textarea></td>
			</tr>
			<tr>
				<td>
				<b>Skype:</b>
				</td>
				<td><textarea class='user-fields' id="skype"><?php echo $cur_user->getSkype(); ?></textarea></td>
			</tr>
			<tr>
				<td>
				<b>Phone:</b>
				</td>
				<td><textarea class='user-fields' id="phone"><?php echo $cur_user->getPhone(); ?></textarea></td>
			</tr>
			<tr>
				<td>
				<b>Url:</b>
				</td>
				<td><textarea class='user-fields' id="url"><?php echo $cur_user->getUrl(); ?></textarea></td>
			</tr>
		</table>
	</div>
	</br>
	<b style='color:blue'>JOB EXPERIENCE:</b></br></br>
	<div id='ajaxjobs'>
	<?php/* if (array_key_exists('CVDATA', $cvdata)):?>
		<?php foreach($cvdata['CVDATA'] as $cvmanagment):?>
			<?php foreach($cvmanagment as $cv):?>
				<div id = "jobs" style="margin-left:20px">		
					<a name="job<?php echo $cv->getId() ?>"></a>
					<select id="sel-<?php echo $cv->getId() ?>" size='1'>
					<?php foreach($cvdata['EMPLOYERS'] as $EMPLOYER):?>
					  <option id='<?php echo $EMPLOYER['ID'];?>'  
					  <?php if ($cv->getEmployerId() == $EMPLOYER['ID']) echo 'selected'; ?>><?php echo $EMPLOYER['NAME']; ?></option>
					<?php endforeach; ?>
					</select>
			
					</br>
					<input type="date" name="calendar" id='calendarfrom-<?php echo $cv->getId() ?>' value="<?php echo $cv->getDateFrom()?>">&nbsp;&nbsp;&nbsp;till&nbsp;&nbsp;&nbsp;<input type="date" name="calendar" id='calendarto-<?php echo $cv->getId() ?>' value="<?php echo $cv->getDateTo()?>">
					
					<textarea class='cv-descr' id="cv-<?php echo $cv->getId() ?>"><?php echo $cv->getDescription(); ?></textarea>
					<textarea class='cv-tech' id="cv-<?php echo $cv->getId() ?>"><?php echo $cv->getTechnologies(); ?></textarea>
					<a id="remove-<?php echo $cv->getId(); ?>"class="delete-cv">Delete This Experience</a>&nbsp;|&nbsp
					<a id="<?php echo $cv->getId(); ?>" class="save-cv">Save This Experience</a>
					<hr>
				</div>
			<?php endforeach; ?>
		<?php endforeach; ?>
	<?php endif;*/?>
	</div>
</div>
<div class="clear-both"></div>